/**
 * Design Tokens - Public API
 *
 * Semantic tokens generated by Color Intelligence v5.x
 * with WCAG 3.0 conformance validation.
 *
 * @module lib/theme/tokens
 */

// ============================================
// Bottom Navigation Tokens
// ============================================

export {
  generateBottomNavTokens,
  exportToCSS,
  exportToJSON,
  getDefaultBottomNavTokens,
  type BottomNavTokenSet,
  type BottomNavTokensConfig,
  type BottomNavTokensResult,
  type APCAScore,
} from './bottom-nav-tokens';
