# =============================================================================
# Google Cloud Build - Lead Service
# Builds and deploys to Cloud Run
# =============================================================================
#
# CONFIGURACIÓN INICIAL (ejecutar una vez):
#
# 1. Crear proyecto en GCP:
#    gcloud projects create zuclubit-crm-staging --name="Zuclubit CRM Staging"
#    gcloud config set project zuclubit-crm-staging
#
# 2. Habilitar APIs necesarias:
#    gcloud services enable cloudbuild.googleapis.com run.googleapis.com artifactregistry.googleapis.com
#
# 3. Crear repositorio de Artifact Registry:
#    gcloud artifacts repositories create zuclubit-crm --repository-format=docker --location=us-central1
#
# 4. Dar permisos a Cloud Build para desplegar en Cloud Run:
#    gcloud projects add-iam-policy-binding zuclubit-crm-staging \
#      --member="serviceAccount:$(gcloud projects describe zuclubit-crm-staging --format='value(projectNumber)')@cloudbuild.gserviceaccount.com" \
#      --role="roles/run.admin"
#    gcloud projects add-iam-policy-binding zuclubit-crm-staging \
#      --member="serviceAccount:$(gcloud projects describe zuclubit-crm-staging --format='value(projectNumber)')@cloudbuild.gserviceaccount.com" \
#      --role="roles/iam.serviceAccountUser"
#
# 5. Configurar variables de entorno en Secret Manager:
#    gcloud secrets create lead-service-env --data-file=.env.staging
#
# DEPLOY MANUAL:
#    cd services/lead-service
#    gcloud builds submit --config=cloudbuild.yaml
#
# =============================================================================

substitutions:
  _SERVICE_NAME: lead-service
  _REGION: us-central1
  _REPOSITORY: zuclubit-crm

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build'

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
    id: 'push'
    waitFor: ['build']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=staging'
      - '--update-secrets'
      - 'POSTGRES_HOST=lead-service-env:POSTGRES_HOST,POSTGRES_PORT=lead-service-env:POSTGRES_PORT,POSTGRES_DB=lead-service-env:POSTGRES_DB,POSTGRES_USER=lead-service-env:POSTGRES_USER,POSTGRES_PASSWORD=lead-service-env:POSTGRES_PASSWORD,SUPABASE_URL=lead-service-env:SUPABASE_URL,SUPABASE_ANON_KEY=lead-service-env:SUPABASE_ANON_KEY,SUPABASE_SERVICE_KEY=lead-service-env:SUPABASE_SERVICE_KEY,SUPABASE_JWT_SECRET=lead-service-env:SUPABASE_JWT_SECRET'
    id: 'deploy'
    waitFor: ['push']

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout (10 minutes)
timeout: '600s'
